name: Cypress Tests

on: [push]

jobs:
    cypress-run:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4.1.1

            - name: Cypress run
              uses: loseshoes
              with:
                build: npm run build
                start: npm start
                browser: chrome


